version: '2'
services:
    odosiisvc3-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ODOSIIsvc3/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ODOSIIsvc3
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
